// <auto-generated />
using System;
using Cinema.Services.SessionAPI.Persistence.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Services.SessionAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.MovieTheater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieTheaterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MovieTheaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 1,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 1,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 1,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterNumber = 6
                        });
                });

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieTheaterId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieTheaterId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "A-1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "A-2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "A-3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "A-4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "A-5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "B-1"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "B-2"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "B-3"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "B-4"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "B-5"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "C-1"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "C-2"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "C-3"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "C-4"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "C-5"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "D-1"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "D-2"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "D-3"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "D-4"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 1,
                            SeatNumber = "D-5"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "A-1"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "A-2"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "A-3"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "A-4"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "A-5"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "B-1"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "B-2"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "B-3"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "B-4"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "B-5"
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "C-1"
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "C-2"
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "C-3"
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "C-4"
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "C-5"
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "D-1"
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "D-2"
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "D-3"
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "D-4"
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 2,
                            SeatNumber = "D-5"
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "A-1"
                        },
                        new
                        {
                            Id = 42,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "A-2"
                        },
                        new
                        {
                            Id = 43,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "A-3"
                        },
                        new
                        {
                            Id = 44,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "A-4"
                        },
                        new
                        {
                            Id = 45,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "A-5"
                        },
                        new
                        {
                            Id = 46,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "B-1"
                        },
                        new
                        {
                            Id = 47,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "B-2"
                        },
                        new
                        {
                            Id = 48,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "B-3"
                        },
                        new
                        {
                            Id = 49,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "B-4"
                        },
                        new
                        {
                            Id = 50,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "B-5"
                        },
                        new
                        {
                            Id = 51,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "C-1"
                        },
                        new
                        {
                            Id = 52,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "C-2"
                        },
                        new
                        {
                            Id = 53,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "C-3"
                        },
                        new
                        {
                            Id = 54,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "C-4"
                        },
                        new
                        {
                            Id = 55,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "C-5"
                        },
                        new
                        {
                            Id = 56,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "D-1"
                        },
                        new
                        {
                            Id = 57,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "D-2"
                        },
                        new
                        {
                            Id = 58,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "D-3"
                        },
                        new
                        {
                            Id = 59,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "D-4"
                        },
                        new
                        {
                            Id = 60,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 3,
                            SeatNumber = "D-5"
                        },
                        new
                        {
                            Id = 61,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "A-1"
                        },
                        new
                        {
                            Id = 62,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "A-2"
                        },
                        new
                        {
                            Id = 63,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "A-3"
                        },
                        new
                        {
                            Id = 64,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "A-4"
                        },
                        new
                        {
                            Id = 65,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "A-5"
                        },
                        new
                        {
                            Id = 66,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "B-1"
                        },
                        new
                        {
                            Id = 67,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "B-2"
                        },
                        new
                        {
                            Id = 68,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "B-3"
                        },
                        new
                        {
                            Id = 69,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "B-4"
                        },
                        new
                        {
                            Id = 70,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "B-5"
                        },
                        new
                        {
                            Id = 71,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "C-1"
                        },
                        new
                        {
                            Id = 72,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "C-2"
                        },
                        new
                        {
                            Id = 73,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "C-3"
                        },
                        new
                        {
                            Id = 74,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "C-4"
                        },
                        new
                        {
                            Id = 75,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "C-5"
                        },
                        new
                        {
                            Id = 76,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "D-1"
                        },
                        new
                        {
                            Id = 77,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "D-2"
                        },
                        new
                        {
                            Id = 78,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "D-3"
                        },
                        new
                        {
                            Id = 79,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "D-4"
                        },
                        new
                        {
                            Id = 80,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 4,
                            SeatNumber = "D-5"
                        },
                        new
                        {
                            Id = 81,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "A-1"
                        },
                        new
                        {
                            Id = 82,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "A-2"
                        },
                        new
                        {
                            Id = 83,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "A-3"
                        },
                        new
                        {
                            Id = 84,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "A-4"
                        },
                        new
                        {
                            Id = 85,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "A-5"
                        },
                        new
                        {
                            Id = 86,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "B-1"
                        },
                        new
                        {
                            Id = 87,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "B-2"
                        },
                        new
                        {
                            Id = 88,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "B-3"
                        },
                        new
                        {
                            Id = 89,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "B-4"
                        },
                        new
                        {
                            Id = 90,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "B-5"
                        },
                        new
                        {
                            Id = 91,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "C-1"
                        },
                        new
                        {
                            Id = 92,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "C-2"
                        },
                        new
                        {
                            Id = 93,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "C-3"
                        },
                        new
                        {
                            Id = 94,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "C-4"
                        },
                        new
                        {
                            Id = 95,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "C-5"
                        },
                        new
                        {
                            Id = 96,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "D-1"
                        },
                        new
                        {
                            Id = 97,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "D-2"
                        },
                        new
                        {
                            Id = 98,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "D-3"
                        },
                        new
                        {
                            Id = 99,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "D-4"
                        },
                        new
                        {
                            Id = 100,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 5,
                            SeatNumber = "D-5"
                        },
                        new
                        {
                            Id = 101,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "A-1"
                        },
                        new
                        {
                            Id = 102,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "A-2"
                        },
                        new
                        {
                            Id = 103,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "A-3"
                        },
                        new
                        {
                            Id = 104,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "A-4"
                        },
                        new
                        {
                            Id = 105,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "A-5"
                        },
                        new
                        {
                            Id = 106,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "B-1"
                        },
                        new
                        {
                            Id = 107,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "B-2"
                        },
                        new
                        {
                            Id = 108,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "B-3"
                        },
                        new
                        {
                            Id = 109,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "B-4"
                        },
                        new
                        {
                            Id = 110,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "B-5"
                        },
                        new
                        {
                            Id = 111,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "C-1"
                        },
                        new
                        {
                            Id = 112,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "C-2"
                        },
                        new
                        {
                            Id = 113,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "C-3"
                        },
                        new
                        {
                            Id = 114,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "C-4"
                        },
                        new
                        {
                            Id = 115,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "C-5"
                        },
                        new
                        {
                            Id = 116,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "D-1"
                        },
                        new
                        {
                            Id = 117,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "D-2"
                        },
                        new
                        {
                            Id = 118,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "D-3"
                        },
                        new
                        {
                            Id = 119,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "D-4"
                        },
                        new
                        {
                            Id = 120,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieTheaterId = 6,
                            SeatNumber = "D-5"
                        });
                });

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.SeatSessionStatus", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservedStatus")
                        .HasColumnType("int");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId", "SeatId");

                    b.HasIndex("SeatId");

                    b.HasIndex("SessionId", "SeatId")
                        .IsUnique();

                    b.ToTable("SeatSessionStatus");
                });

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("MovieTheaterId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieTheaterId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            MovieTheaterId = 1,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            MovieTheaterId = 1,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            MovieTheaterId = 1,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            MovieTheaterId = 2,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            MovieTheaterId = 2,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            MovieTheaterId = 2,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3,
                            MovieTheaterId = 3,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3,
                            MovieTheaterId = 3,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 4,
                            MovieTheaterId = 4,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 5,
                            MovieTheaterId = 5,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 31, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 6,
                            MovieTheaterId = 6,
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.Seat", b =>
                {
                    b.HasOne("Cinema.Services.SessionAPI.Domain.Entities.MovieTheater", "MovieTheater")
                        .WithMany("Seats")
                        .HasForeignKey("MovieTheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieTheater");
                });

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.SeatSessionStatus", b =>
                {
                    b.HasOne("Cinema.Services.SessionAPI.Domain.Entities.Seat", "Seat")
                        .WithMany("SeatSessionStatuses")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cinema.Services.SessionAPI.Domain.Entities.Session", "Session")
                        .WithMany("SeatSessionStatuses")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.Session", b =>
                {
                    b.HasOne("Cinema.Services.SessionAPI.Domain.Entities.MovieTheater", "MovieTheater")
                        .WithMany("Sessions")
                        .HasForeignKey("MovieTheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieTheater");
                });

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.MovieTheater", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.Seat", b =>
                {
                    b.Navigation("SeatSessionStatuses");
                });

            modelBuilder.Entity("Cinema.Services.SessionAPI.Domain.Entities.Session", b =>
                {
                    b.Navigation("SeatSessionStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
